name: atmos_surf_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  atmos_binary_buffer:
    git: git@github.com:Atom735/atmos_binary_buffer.git
  atmos_logger:
    git: git@github.com:Atom735/atmos_logger.git
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  firebase_core_desktop: ^0.1.1-dev.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  meta: ^1.7.0
  shared_preferences: ^2.0.13
  sqlite3:
    git:
      url: git@github.com:Atom735/sqlite3.dart.git
      path: sqlite3
  url_launcher: ^6.0.20
  yaml: ^3.1.0

dev_dependencies:
  atmos_lints:
    git: git@github.com:Atom735/atmos_lints.git
  flutter_test:
    sdk: flutter
  test: ^1.19.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
